name: 'Setup PyRustor Development Environment'
description: 'Sets up Python, Rust, uv, and just for PyRustor development'

inputs:
  python-version:
    description: 'Python version to use'
    required: true
    default: '3.10'
  rust-components:
    description: 'Additional Rust components to install'
    required: false
    default: ''
  cache-key-suffix:
    description: 'Additional suffix for cache keys'
    required: false
    default: ''
  install-dependencies:
    description: 'Whether to install project dependencies'
    required: false
    default: 'true'
  skip-version-check:
    description: 'Whether to skip version consistency check'
    required: false
    default: 'false'

outputs:
  python-version:
    description: 'The Python version that was installed'
    value: ${{ steps.setup-python.outputs.python-version }}
  rust-version:
    description: 'The Rust version that was installed'
    value: ${{ steps.setup-rust.outputs.rustc-version }}

runs:
  using: 'composite'
  steps:
    - name: Setup Python
      id: setup-python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        python-version: ${{ inputs.python-version }}
        enable-cache: false

    - name: Setup Rust
      id: setup-rust
      uses: dtolnay/rust-toolchain@stable
      with:
        components: ${{ inputs.rust-components }}

    - name: Setup Advanced Caching
      uses: ./.github/actions/cache-setup
      with:
        cache-type: 'build'
        cache-key-suffix: ${{ inputs.cache-key-suffix }}
        python-version: ${{ inputs.python-version }}

    - name: Install just
      uses: extractions/setup-just@v3

    - name: Fix macOS Python 3.9 gettext dependency
      if: runner.os == 'macOS' && inputs.python-version == '3.9'
      shell: bash
      run: |
        echo "🔧 Installing gettext for Python 3.9 on macOS..."
        # Install gettext via Homebrew
        brew install gettext

        # Create symlink to ensure Python can find the library
        # The Python 3.9.23 binary expects libintl.8.dylib in /usr/local/opt/gettext/lib/
        if [ ! -f "/usr/local/opt/gettext/lib/libintl.8.dylib" ]; then
          echo "Creating symlink for libintl.8.dylib..."
          sudo mkdir -p /usr/local/opt/gettext/lib
          # Find the actual gettext installation
          GETTEXT_LIB=$(brew --prefix gettext)/lib/libintl.8.dylib
          if [ -f "$GETTEXT_LIB" ]; then
            sudo ln -sf "$GETTEXT_LIB" /usr/local/opt/gettext/lib/libintl.8.dylib
            echo "✅ Symlink created: /usr/local/opt/gettext/lib/libintl.8.dylib -> $GETTEXT_LIB"
          else
            echo "❌ Could not find gettext library at $GETTEXT_LIB"
            exit 1
          fi
        else
          echo "✅ libintl.8.dylib already exists"
        fi

        # Verify the fix
        echo "🔍 Verifying Python 3.9 can start..."
        python3.9 --version
        echo "✅ Python 3.9 gettext dependency fixed"

    - name: Install dependencies
      if: inputs.install-dependencies == 'true'
      shell: bash
      run: just ci-install
